### ISSUE TITLE
Quota management needs to be more robust 

### ISSUE THREAD

**Issue by jaycedowell** [lwa-project/ovro_data_recorder#21]
See: https://github.com/ovro-lwa/lwa-issues/issues/213

**Comment by jaycedowell** [comment]
https://github.com/ovro-lwa/lwa-issues/issues/211 also seems related where slow downs in the quota management impact the status and performance updates.

**Comment by caseyjlaw** [comment]
I think I was seeing oddities related to data recorders for slow visibilities. In one case, I saw a recorder display the command line arguments in the logging, but then did not start the logging loop (e.g., with lags, etc). After a while, the quota management logged that it removed 5000 files. Then, the regular logging loop started up and all seemed fine.
Another potentially relevant point: the two data recorders on a node show very different disk levels, but they write to the same disk. Not sure how that could happen.

**Comment by jaycedowell** [comment]
I've tried several different things to try to fix that but the fundamental problem is that quota stuff is slow when there are a large number of files.  The only two remaining ideas I have are to either:
 1) move the quota management stuff into its own thread or
 2) turn off the quota management entirely.

(1) doesn't actually address the problem and I don't know if it will work well with lustre.  (2) is probably the better solution but quota management would still need to happen somewhere .

On your second point:  were they both slow recorders or some mix of slow, fast, and power beam?

**Comment by caseyjlaw** [comment]
I was only using slow recorders. I saw the statement about removing files in one log file, but didn't compare to the other one.
I'd be ok with turning off quota management and setting a policy for disk usage in the short term. Currently, people are struggling with observing for a variety of reasons (last logging before my run was first week of January), so I'd like to make it as easy as possible.

**Comment by jaycedowell** [comment]
The current setup for the services is that there are two slow recorder for cal/im node and only one of them has file deletion part of the quota management enabled.  That could explain what you are seeing in the logs.

**Comment by caseyjlaw** [comment]
I guess I was more confused the the fact that the monitor points of the two recorders was different, despite sharing the same disk on one server. But maybe that's an artifact of the design you mentioned.

**Comment by jaycedowell** [comment]
Monitor points as in information in the log or as in something exposed through the etcd interface?

**Comment by caseyjlaw** [comment]
The etcd info, as accessed via your mcs `Client` class.
I display that on the Monitoring Dashboard, which you can get to via https://ovro-lwa.github.io/ (and tunneling to lxdlwacr).

**Comment by jaycedowell** [comment]
That's strange, I wouldn't have expected that.  What exactly were the differences?

**Comment by yupinghuang** [comment]
I suspect it's the recursive stat calls that's giving it trouble. For measurement sets...I mean we know how big each measurement set is, so we can probably just list the directories under data0x/slow (or fast) and then multiply the number of directories by the known size.

**Comment by jaycedowell** [comment]
I had tried something similar to that where I found the size of each directory once and then cached it.  It did help but the quota management would still get into a situation where deleting took minutes.

**Comment by yupinghuang** [comment]
hmmmm. probably still helpful (eventually) to stick quota management in its own thread and have it run less frequently and not block logging. With or without lustre, I think we have some overhead room for the usage to go over so that even if deletion takes ~30min, we should still be fine. And maybe it can delete an hour worth (or some configurable amount) of data at a time?

**Comment by yupinghuang** [comment]
https://github.com/lwa-project/ovro_data_recorder/pull/23 makes deletion a less busy wait on the spawned rm process. This seems to help with rm taking a while and blocking all other threads (yay GIL).

The update (glob and stat) still takes anywhere from 0.3 s (probably cached) to 10 s (the typical number) to 400s since glob does block.  Could probably Popen that too but a few minutes seem tolerable.

With lustre coming on I'm still worried about the glob and stat, probably should cache the list of files written on etcd or somewhere and not glob all the time, but we'll see how the newer version of lustre does.

Also started a branch to make quota management its own process.

**Comment by jaycedowell** [comment]
@yupinghuang thanks for the pull request.  I'll leave some comments on it.

With regards to making quota management its own process I think that is a good idea.  The data recorders should only focus on recording data and quota management should be its own thing.  Maybe that ultimately needs its own repo depending on the scope/features.

**Comment by jaycedowell** [comment]
Addressed with #23.
