### ISSUE TITLE
feature request: partition visibility folder

### ISSUE THREAD

**Issue by yupinghuang** [lwa-project/ovro_data_recorder#36]
reason is that lots of things are excruciatingly slow on zfs and lustre for directories with large number of subdirectories (same reason why git breaks a hash into lots of sub directories when it stores diffs...). Leading reason for packet loss of the data recorder.

so here's the request: we do

`slow/xxMHz/2023-01-01/01/` for all the stuff in 01 hours at xx MHz. That makes 360 sub-directories per directory, which is somewhat manageable.

for fast viz that's 3600 sub-dirs, which might still be a little too much. There's a chance we have to break it by minute (or write 10 timestamps per ms?)

 I wanted comments from people who've been working with data before making this an actual thing.

**Comment by caseyjlaw** [comment]
I'm not knowledgeable enough about file systems to comment, but are there guidelines on the number of files in a subdirectory?
Not clear to me why you need the `xxMHz` level within a given `dataxx` directory.

**Comment by jaycedowell** [comment]
3b0a87a effectively breaks quota management as it is currently setup because it will find that `xxMHz` directory and eventually blow it away.  I wonder if the thing do to might be to swap the directory order to something like `slow/YYYY-mm-dd/HH/xxMHz` or even eliminate the `xxMHz` sub-directory altogether.  With that alternate ordering deletion would be day-by-day which seems reasonable, provided that fits within the available disk space.

**Comment by jaycedowell** [comment]
Thinking about this more maybe that doesn't work either.  It looks like you only get one shot to set the size for a directory so the first time a new `YYYY-mm-dd` is seen is the only time a size is set.  That's it.

**Comment by jaycedowell** [comment]
I've been thinking about this some more in light of #38.  I think this can work if we use a structure like `slow/YYYY-mm-dd/HH/<your_data_here.ms>` and then switch to a time-based quota management.  So rather than totaling up disk space for every MS in every sub-directory, the quota management looks at YYYY-mm-DD and HH to come up with an age.  That age is then compared to a quota size in seconds to determine what stays and what goes.

**Comment by caseyjlaw** [comment]
That seems reasonable.
Maybe also include a spot check of the size of one of the hour-based directories? Or one could imagine a hybrid approach, where there is a size quota, but only computed from n_dirs*size_of_one. When it is too large, then you remove the oldest.

**Comment by yupinghuang** [comment]
So when we're on lustre. It would look like `/lustre/data/xxMhz` where all subbands live under the same directory. Having the extra dataxx isn't really necessary.

re blowing dirs away -- can we have each data recorder be in charge of its subband?

long term - we probably have the writer thread pass the latest file via a queue to the quota thread/process. Or have quota go through some other api for fast scandir. I suggest that we wait a bit...

**Comment by jaycedowell** [comment]
Here's a summary of what is currently testing:

The biggest structural change is that there is now a `TimeStorageLogger` class that is used by the vis. recorders for quota management[^1].  This quota manager runs on a per-recorder basis and requires a specific directory structure of `##MHz/YYYY-MM-DD/HH/your_measurement_set_here.ms`.  Here `##MHz` is the current frequency being processed in the data recorder (as retrieved from the `latest_frequency` monitor point).  The `YYYY-MM-DD` and `HH` directories are used to create a timestamp that is used for the quota enforcement.  Once a timestamp is out of range of the quota (now specified as a time, i.e., "1w" for 1 week) everything in that `YYYY-MM-DD` and/or `HH` directory is removed.  I've tried to make this touch lustre as little as possible - it only looks in the active `##MHz` directory and it only recurs down to the `HH` level.  The side effect of this is that `TimeStorageLogger` as no idea how much disk space is used, only how long files _seem to have existed based on the path_.

Other things to note:
 * MS are now staged in `/fast/pipeline/temp` before they are copied over.  This should help with fast vis. recording since lustre will only gets a single `cp` command when the MS is complete and is ready to be moved over.
 * I've tried to make the MS writer touch lustre as little as possible by internally keeping track of the correct `##MHz/YYYY-MM-DD/HH` directory so that it isn't trying to constant see if it exists already.
 * There is a new data retention feature with `TimeStorageLogger` that will allow data to be exempted from the quota enforcement.  After data have been written for a given `HH` hour you can save it by renaming it to `HH_retain`.  That will tell the quota manager to skip deleting that directory once it becomes too old[^2].  You can do the same thing at the `YYYY-MM-DD` level after the day has finished to save all 24 hours.  Things will be eligible for removal again when they are renamed to remove the `_retain`.  
 * I've tried to make things more robust in the case of higher load but resource starvation events, like what happened last week, are still really bad.

Interesting caveats about the new quota manager:
 * `TimeStroageLogger` uses the current system time to determine timestamp age.  That means if the system is shutdown for an extended period of time, once the quota manager starts up it will being deleting everything that is too old.
 * There is an interested edge case when the system is retuned.  As soon as the quota manager gets a new `latest_frequency` it will stop quota enforcement on the old frequency and start on the new one.  This can go two ways:
     *  If the new frequencies are unique relative to the previous set then all the old frequencies are left untouched until the system moves back.  At that point you run into the first caveat listed here.
     * If the new frequencies are not unique, e.g., I'm thinking of the case for the bistatic radar tests where the frequencies are slid down by a subband, then quota enforcement will continue on the new frequencies _as well as those that are common with the old setup_.

I think the thing to do now is to let the system run for a while to see how this/recording to lustre holds up.  The three things to look for are (1) if it seems to work reliably when people are using the nodes, (2) if power beam recording works with lustre[^3], and (3) to see if the memory leak reported in https://github.com/ovro-lwa/lwa-issues/issues/445 really is fixed.  For (3) at least one of the slow recorders should _not_ be restarted for a period of time to make sure that the memory footprint doesn't grow continuously.

[^1]:  The old `StorageLogger` is now called `DiskStorageLogger` and is still used by the power beams.
[^2]:  The quota manager should be able to correctly handle the case where a single `HH_retain` is marked and not delete its parent `YYYY-MM-DD` directory.  The other non-retained `HH` directories should be deleted as the quota in enforced.
[^3]:  For power beams my concern is with all of the little flushes every ~10 s that are needed as part of the "single writer, multiple reader" support that was merged with #39.

**Comment by yupinghuang** [comment]
Thanks! I’d like to note that ‘mv’ on lustre is blazing fast so that’s the
preferred way of saving data from the buffer.

**Comment by caseyjlaw** [comment]
Wonderful, Jayce. Thanks for getting this deployed.
On the data volume calculation point, I may have a related development in the [scheduler issue](https://github.com/ovro-lwa/lwa-issues/issues/322). I think we need a way to track scheduled observations, their output, and associate it with array health/state.
I'll play with creating a database to track observations and metadata. I could include a field with data volume that may be useful for the data recorders.
